version: '3'
services:
  php:
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 9000:80
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mapstuff
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
